language: python

os:
- linux

dist:
- bionic # Ubuntu 18.04 LTS Bionic Beaver
#- xenial # Ubuntu 16.04 LTS Xenial Xerus
# (not avarable) Ubuntu 20.04 LTS Focal Fossa
#- Precise # Ubuntu 12.04 LTS Precise Pangolin
#- Trusty # Ubuntu 14.04 LTS Trusty Tahr
# multi dist version: https://github.com/travis-ci/travis-rubies/blob/build/.travis.yml


# cache:
#   directories:
#   - node_modules

#before_install:
#- npm install

before_script:
- pip install -r requirements.txt

script: # TODO: muovere in jobs
- mkdir -p out1 out2 out3
- python3 presolve1.py
- python3 presolve2.py
#- python3 presolve3.py
- python3 bSolution2.py

#after_script:
#- greenkeeper-lockfile-upload

#after_success:
#- npm run-script coveralls

# env:
#   global:
#     - PIPPOzzo=no # fix windows

notifications:
  email:
    on_success: never
    on_failure: change
